name: empresa_dev_monorepo

packages:
  - apps/*
  - packages/*

command:
  bootstrap:
    runPubGetInParallel: true
  clean:
    hooks:
      post: flutter clean

scripts:
  analyze:
    run: melos exec -- "dart analyze ."
    description: Analiza todos los paquetes del monorepo
  test:
    run: melos exec --scope="*_core" -- "dart test"
    description: Tests unitarios de los packages (librerías puras Dart)
  test:app:
    run: cd apps/empresa_dev && flutter test --exclude-tags integration
    description: Tests de la app Flutter
  analyze:app:
    run: cd apps/empresa_dev && flutter analyze
    description: Analiza solo la app
  build:windows:
    run: cd apps/empresa_dev && flutter build windows --release
    description: Build Release de la app para Windows
  run:app:
    run: cd apps/empresa_dev && flutter run -d windows
    description: Ejecuta la app en Windows
