import { chromium } from '@playwright/test';
const b = await chromium.launch();
const ctx = await b.newContext({ locale: 'es-MX' });
const p = await ctx.newPage();
await p.goto('http://localhost:1420');
await p.waitForTimeout(400);
await p.getByRole('button', { name: /^Idioma$/i }).click();
await p.locator('.header-dropdown .dropdown-menu .dropdown-item', { hasText: 'EN' }).last().click();
await p.waitForTimeout(400);
const all = await p.evaluate(() => [...document.querySelectorAll('.subtitle, .app-header h1')].map(e => ({tag:e.tagName, cls:e.className, text:e.textContent?.slice(0,50)})));
console.log(JSON.stringify(all, null, 2));
await b.close();
